# exportpdf.py
# Converts the generated export.md file into export.pdf using markdown-pdf.
# Includes preprocessing to add HTML anchors to headings.

import os
import re
import sys
import logging
import traceback # Import traceback

# --- Attempt to import required library ---
try:
    from markdown_pdf import MarkdownPdf, Section
except ImportError:
    print("❌ Error: Required library 'markdown-pdf' or its dependency 'PyMuPDF' not found.")
    print("Please install it: pip install markdown-pdf PyMuPDF")
    sys.exit(1)

# --- Configuration ---
# Define the input Markdown file name (generated by generator.py)
MARKDOWN_INPUT_FILE = 'export.md'
# Define the desired output PDF file name
PDF_OUTPUT_FILE = 'export.pdf'

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s')

# --- Helper Functions (from provided script) ---

def generate_anchor_id(text):
    """
    Generates a simple, URL-friendly anchor ID from heading text.
    """
    # Remove potential existing HTML tags
    text = re.sub(r'<[^>]+>', '', text)
    # Remove punctuation except hyphens, convert to lowercase
    text = re.sub(r'[^\w\s-]', '', text).strip().lower()
    # Replace whitespace sequences with a single hyphen
    anchor_id = re.sub(r'\s+', '-', text)
    # Remove leading/trailing hyphens
    anchor_id = anchor_id.strip('-')
    return anchor_id

def add_anchors_to_markdown(md_path):
    """
    Reads a markdown file, adds HTML anchors before H1, H2, H3 headings,
    and overwrites the file.
    """
    logging.info(f"Preprocessing '{md_path}' to add heading anchors...")
    try:
        # Ensure file exists before trying to read
        if not os.path.exists(md_path):
             logging.error(f"Preprocessing failed: Input file '{md_path}' not found.")
             return False

        with open(md_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        processed_lines = []
        added_anchors = set() # Avoid duplicate anchors

        for i, line in enumerate(lines):
            is_prev_line_anchor = i > 0 and re.match(r'<a\s+id=".*?"\s*></a>', lines[i-1].strip())
            match = re.match(r'^(\#{1,3})\s+(.*)$', line.strip()) # Match H1, H2, H3

            if match and not is_prev_line_anchor:
                heading_level = match.group(1)
                heading_text = match.group(2).strip()
                # Strip potential existing links for ID generation
                heading_text_for_id = re.sub(r'<a\s+.*?>.*?</a>', '', heading_text).strip()

                if heading_text_for_id:
                    anchor_id = generate_anchor_id(heading_text_for_id)
                    if anchor_id and anchor_id not in added_anchors:
                        anchor_tag = f'<a id="{anchor_id}"></a>\n'
                        processed_lines.append(anchor_tag)
                        added_anchors.add(anchor_id)

            processed_lines.append(line) # Add original line

        # Overwrite the original file
        with open(md_path, 'w', encoding='utf-8') as f:
            f.writelines(processed_lines)

        logging.info(f"Finished preprocessing '{md_path}'.")
        return True
    except Exception as e:
        logging.error(f"Error during markdown preprocessing: {e}", exc_info=True)
        return False

# --- Main Conversion Function ---

def convert_markdown_to_pdf(md_path, pdf_path):
    """
    Preprocesses markdown file to add anchors, then converts it to PDF.

    Args:
        md_path (str): The path to the input Markdown file.
        pdf_path (str): The path where the output PDF file will be saved.
    """
    logging.info(f"Starting conversion process for '{md_path}'...")

    # Check if the input Markdown file exists before preprocessing
    if not os.path.exists(md_path):
        logging.error(f"Error: Input file '{md_path}' not found.")
        return False # Indicate failure

    # --- Add preprocessing step ---
    if not add_anchors_to_markdown(md_path):
        logging.error("Aborting conversion due to preprocessing error.")
        return False # Indicate failure
    # --- End preprocessing step ---

    logging.info(f"Proceeding to PDF conversion for the preprocessed '{md_path}'...")
    try:
        # Read the content of the (now modified) Markdown file
        logging.info(f"Reading preprocessed content from '{md_path}'...")
        with open(md_path, 'r', encoding='utf-8') as f:
            markdown_content = f.read()
        logging.info("Content read successfully.")

        # Create an instance of the MarkdownPdf class (default toc_level=0)
        pdf = MarkdownPdf()
        logging.info("MarkdownPdf object created (default toc_level).")

        # Create a Section object with the markdown content
        # *** MODIFICATION: Set toc=False for the section ***
        sec = Section(markdown_content, toc=False)
        logging.info("Section object created (toc=False).")


        # Add the section to the PDF object
        logging.info("Adding content as a section to the PDF...")
        pdf.add_section(sec)
        logging.info("Section added.")

        # Save the PDF to the specified file path
        logging.info(f"Saving PDF to '{pdf_path}'...")
        pdf.save(pdf_path)

        # Check if the output PDF file was created
        if os.path.exists(pdf_path):
            logging.info(f"Successfully converted '{md_path}' to '{pdf_path}'!")
            return True # Indicate success
        else:
            logging.error(f"Saving process completed, but output file '{pdf_path}' was not found.")
            return False # Indicate failure

    except FileNotFoundError:
        logging.error(f"Error: Could not find '{md_path}' after preprocessing.")
        return False
    except IOError as e:
        logging.error(f"Error reading file '{md_path}': {e}")
        return False
    except ValueError as ve:
        # Catch the specific ValueError we saw, just in case this fix wasn't enough
        logging.error(f"ValueError during PDF conversion (likely TOC/Bookmark issue): {ve}")
        logging.error("This might happen if the markdown structure is unusual or contains unexpected elements.")
        logging.debug(traceback.format_exc()) # Log traceback for value error
        return False
    except Exception as e:
        logging.error(f"An unexpected error occurred during PDF conversion:", exc_info=True)
        logging.error("Ensure 'markdown-pdf' & 'PyMuPDF' are installed.")
        return False

# --- Main execution ---
if __name__ == "__main__":
    logging.info(f"Running PDF Export Script...")
    # Call the conversion function with the configured paths
    success = convert_markdown_to_pdf(MARKDOWN_INPUT_FILE, PDF_OUTPUT_FILE)

    if success:
        logging.info("PDF generation script finished successfully.")
        sys.exit(0) # Exit with success code
    else:
        logging.error("PDF generation script failed.")
        sys.exit(1) # Exit with error code
# --- End Main execution ---
